### ISSUE TITLE
Version tags missing

### ISSUE THREAD

**Issue by pavel-a** [STMicroelectronics/STM32CubeL4#1]
You wrote in readme.md that "major releases are Tagged" - but there's no tagged commits. Can you tag the major releases, please?

Tagged versions will be visible as "Releases" in the menu on top.

**Comment by CCASTM** [comment]
Hello Pavel,
This is a mistake in our recent publications. Will be corrected today
Regards
Christophe

**Comment by ASELSTM** [comment]
Dear Pavel,

Thank you for pointing out this issue. Indeed, the tag was not added during the package publication. The tag have been added now in the STM32CubeL4 package, the issue is therefore fixed and will be closed.

With regards
