### ISSUE TITLE
linker scripts licencing

### ISSUE THREAD

**Issue by khalifima** [STMicroelectronics/STM32CubeL4#2]
is this file really meant to be proprietary license. the other linker scripts are BSD3 
https://github.com/STMicroelectronics/STM32CubeL4/blob/master/Projects/NUCLEO-L4R5ZI/Templates/SW4STM32/STM32L4R5ZI_NUCLEO/STM32L4R5ZITx_FLASH.ld

**Comment by ALABSTM** [comment]
Hi Khalifima,

Please let me introduce @CCASTM who will answer your question about the license aspect.

With regards,

**Comment by khalifima** [comment]
@ALABSTM thanks for your reply. I consider a no answer as a yes answer. So I will write a linker script and put it as a free license EPL2. BR
