### ISSUE TITLE
How use CubeMX extract 32L4R9IDISCOVERY board demo?

### ISSUE THREAD

**Issue by zhouchuanfu** [STMicroelectronics/STM32CubeL4#33]
Dear all:
    I want to use STM32CubeMx or STM32CubeIDE to generate official demo of the this board, but not find that at STM32CubeMX->New Project->Example Selector->Board.

**Comment by ALABSTM** [comment]
Hi @zhouchuanfu,

Thank you for your question. Actually, the board name in Cube MX is `STM32L4R9I-DISCO`. I hope this helps.

You can report this to the Cube MX team, not through this support channel however. Indeed, this one is dedicated to aspects related to the software **published within** this repository. Aspects like those related to ecosystem and tools are rather treated at **ST Community** level, precisely within the [Cube MX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated section in this case.

Please allow me to close this issue now. We are looking forward to reading from you.

With regards,

**Comment by zhouchuanfu** [comment]
Hi @ALABSTM,
Thank you for your response, I will to go to **ST Community** post this question.
Thank you again.
