### ISSUE TITLE
libarm_cortexMlf4_math.a: arm_rfft_fast_init_f32() returns ARM_MATH_ARGUMENT_ERROR for fftLen=128

### ISSUE THREAD

**Issue by sfahrner** [STMicroelectronics/STM32CubeL4#39]
libarm_cortexMlf4_math.a for STM32L4 Release v1.16.0 (5235kB):

When I call arm_rfft_fast_init_f32() with Parameter fftLen = 128, it returns ARM_MATH_ARGUMENT_ERROR although 128 is a valid value.

When I replace the STM32L4 version of libarm_cortexMlf4_math.a with the STM32F4 version (Release V1.24.1), the FFT length 128 is accepted and correctly processed.

**Comment by RKOUSTM** [comment]
Hi @sfahrner,

Thank you for this report. Unfortunately we don't treat aspect related to GCC lib in our GitHub repositories. These files come from Arm and we use them as is. So, these files are out of the scope of STMicroelectronics what about reporting this issue to the [ARM GitHub](https://github.com/ARM-software)?

Please allow me to close this issue now. Thank you again for your contribution.

With regards,
