### ISSUE TITLE
HAL MMC voltage range configuration

### ISSUE THREAD

**Issue by dima-kapustin** [STMicroelectronics/STM32CubeL4#48]
L4 HAL Driver for MMC v1.7

Voltage rage selection allows byte mode only, i.e. [MMC_LOW_VOLTAGE_RANGE or MMC_HIGH_VOLTAGE_RANGE](https://github.com/STMicroelectronics/STM32CubeL4/blob/5e1553e07706491bd11f4edd304e093b6e4b83a4/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_mmc.c#L280).

Some eMMC cards require sector mode selection, i.g. eMMC_HIGH_VOLTAGE_RANGE or eMMC_LOW_VOLTAGE_RANGE, which are defined in [stm32l4xx_hal_mmc.h](https://github.com/STMicroelectronics/STM32CubeL4/blob/5e1553e07706491bd11f4edd304e093b6e4b83a4/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_mmc.h#L359).

I could not find a way to configure high voltage sector mode, i.e. eMMC_HIGH_VOLTAGE_RANGE.

If there is no such a way then a bug shall be filed, I assume.

**Comment by RKOUSTM** [comment]
Hi @dima-kapustin, 

I hope you are fine. The issue you reported has been fixed in the frame of version v1.17.1 of the STM32CubeL4 published recently on GitHub. Thank you again for having reported.

With regards,
