### ISSUE TITLE
Move non-code content to separate repositories

### ISSUE THREAD

**Issue by benedekkupper** [STMicroelectronics/STM32CubeL4#59]
The Documentation and Utilities/Media folders contain no source code, I would strongly advise to remove those content from this repository,. This would highly improve the usability of the git repository as a source code repo, which can be submoduled into other projects. Especially for automated build systems, checking out the repo takes a lot longer due to the extra files.

Possible alternatives would be:
1. Create separate git repositories, add them as submodules to this repo (in case of the Media folder it would also prevent duplicate content between STM32CubeNX repos)
2. Only add web links of content

**Comment by ALABSTM** [comment]
Hi @benedekkupper,

Thank you for tackling this subject and for your proposal. Actually, we already started publishing separately the different components (**e.g.**, HAL-LL, CMSIS, BSP) a firmware package is made of. The [cmsis_device_l4](https://github.com/STMicroelectronics/cmsis_device_l4) and the [stm32l4xx_hal_driver](https://github.com/STMicroelectronics/stm32l4xx_hal_driver) repos are some examples. You can find the complete list [here](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer#content).

The main purpose is to allow users only interested in such components to download them while avoiding the overhead of downloading unwanted ones. This is still being deployed.

Regarding the use of Git submodules, this has been already done to create the [stm32u5-classic-coremw-apps](https://github.com/STMicroelectronics/stm32u5-classic-coremw-apps) repo. We are still studying the impact of introducing such change on existing STM32CubeNX repos. We still cannot communicate a date about such deployment.

Thank you again for your post. I hope my reply could shed more light about the subject. Please allow me to close this issue now. Thank you for your comprehension.

With regards,
