### ISSUE TITLE
Missing License Text

### ISSUE THREAD

**Issue by gojimmypi** [STMicroelectronics/STM32CubeL4#63]
There's a [note](https://github.com/STMicroelectronics/STM32CubeL4/blob/f93a2f74f8e9912405dbf1a297b6df0c423eddf2/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal_flash.h#L12) that 

>  This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component

However [that file](https://github.com/STMicroelectronics/STM32CubeL4/blob/master/Drivers/STM32L4xx_HAL_Driver/License.md) is now blank:

![image](https://user-images.githubusercontent.com/13059545/154821059-236ea0cf-dafb-47cb-a3a6-61f288bbfe44.png)

There's no license at [https://github.com/STMicroelectronics/STM32CubeL4/tree/master/Drivers](https://github.com/STMicroelectronics/STM32CubeL4/tree/master/Drivers)

Perhaps that text refers to the [repo license summary](https://github.com/STMicroelectronics/STM32CubeL4/blob/master/LICENSE.md) ? It seems a bit unusual to simply list the names of the licenses with no other text, but I am certainly not a license expert.

**Comment by RKOUSTM** [comment]
Hi @gojimmypi,

Thank you for your contribution. You are absolutely right about this point. This point has already been raised internally and an update of the license text in the license.md file will be made available in the frame of a future release.

Thank you once more for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
Hi @gojimmypi,

Thank you for your contribution. The issue you pointed out is fixed and now available in GitHub. 

Please allow me then to close this thread. Thank you again for your contribution. We are looking forward to reading from you again.

With regards,
