### ISSUE TITLE
Sample Code for B-L462E-CELL1

### ISSUE THREAD

**Issue by djsg** [STMicroelectronics/STM32CubeL4#65]
How come in this package, there is no project code for B-L462E-CELL1, of which the MCU is an STM32L462REY6TR microcontroller?
Particularly I am looking for sample code for USART communications.

**Comment by ASELSTM** [comment]
Hi @djsg,

The STM32CubeL4 package is proposing a set of USART examples as mentioned in the [STM32CubeProjectsList](https://htmlpreview.github.io/?https://github.com/STMicroelectronics/STM32CubeL4/blob/master/Projects/STM32CubeProjectsList.html). You may refer to theses examples and easily port them to the MCU you are using.  Hope this would help.

With regards,
