### ISSUE TITLE
ST CUBE MX version V1.17.2 & V1.17.1 & V1.16.0 when using a STM32L496QG  MCU 

### ISSUE THREAD

**Issue by SIBA-FEMD** [STMicroelectronics/STM32CubeL4#73]
For the STM32L496QG MCU there are problems with the CUBEMX databases  when using IAR ARM IDE.

This is only an issue for the  STM32L496QG MCU but not the STM32L496ZQ   when using the  ST_NUCLEO-L496ZG .

Please note that  IAR support has spent several hours with me looking at this issue and we determined that was purely a STMCUBEMX problem. 

All tests where carried out with a empty  STMCUBEMX generated application frame and no user code. 

![image](https://user-images.githubusercontent.com/84386395/181255832-5d663aad-983c-4b0b-81dd-0a3e3179af9e.png)

This is the status of the issues with CubeMX .. 

Please note these where reported to ST on the 7th July 2022 ..  As can be seen in the support log. 

Please also see ST support cases : 00160324 & 00160400 & 00161713 which have been sitting idle since 7th July 2022

**Comment by ASELSTM** [comment]
Hi @SIBA-FEMD,

It looks like the mentioned  ST support cases **00160324**,  **00160400** and  **00161713** have been closed so I presume the issue has been addressed.

Please note, however, that this support channel is particularly dedicated to the firmware published within this repository. Reports, requests, and questions related to other topic such as the hardware or the tools (such as STM32CubeMx like in this case), should be submitted to the [ST Community](https://community.st.com/s/).

Please allow me then to close this issue. Thank you for your comprehension.

With regards,
