### ISSUE TITLE
LL_DAC_ConvertData12LeftAligned refers to DHR12R1?

### ISSUE THREAD

**Issue by DaPa** [STMicroelectronics/STM32CubeL4#77]
https://github.com/STMicroelectronics/STM32CubeL4/blob/138f30fa54d60539ab2e4f9baa17cd919a9829dd/Drivers/STM32L4xx_HAL_Driver/Inc/stm32l4xx_ll_dac.h#L1643
should be __DAC_PTR_REG_OFFSET(DACx->DHR12**L**1, ...) there?

**Comment by ARIOSTM** [comment]
Hello DaPa,

Thank you for your remark.
DACx->DHR12R1 here is used as a base address for the macro __DAC_PTR_REG_OFFSET. 
This macro computes the correct register address (DHR12R1, DHR12L1, DHR8R1, DHR12R2, ...) depending on the selected channel.

Best Regards
