### ISSUE TITLE
Adafruit LCD Shield V2 seesaw version not supported

### ISSUE THREAD

**Issue by BKneer** [STMicroelectronics/STM32CubeL4#88]
**Caution**
The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus).
When I've noticed that there is an example for Adafruit TFT shield I've ordered one. Unfortunately just figured out that this newer version with the Seesaw chip is not supported by the example. Also it's quite hard to look into the changes that would be necessary to get it running as the documentation of the old version and the new one is quite limited.

**Describe the set-up**
 * The board (either ST RPN reference or your custom board).
 * IDE or at least the compiler and its version.
I'm using the Nucleo STM32L476 board and the new Seesaw version of Adafruit's TFT shield with joystick and buttons in STM32CubeIde
**Additional context**
It seems that already at the beginning when the code checks for the board to be connected the example fails. 

**Screenshots**

**Comment by ALABSTM** [comment]
Hi @BKneer,

Thank you for this question. As indicated in the [CONTRIBUTING.md](https://github.com/STMicroelectronics/STM32CubeL4/blob/master/CONTRIBUTING.md#3-support-requests-and-questions) file, questions about hardware support and examples porting shall be submitted to the **ST Community**. There you should find the adequate support you are looking for.

Please allow me to close this one. Thank you for your comprehension.

With regards,
